services:
  db:
    image: mysql:8.0
    container_name: redesocial_db_container
    restart: always
    environment:
      MYSQL_DATABASE: redesocial
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - redesocial_net

  web:
    build: .
    container_name: redesocial_web_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db
    networks:
      - redesocial_net

volumes:
  mysql_data:

networks:
  redesocial_net:
    driver: bridge